const FLIGHT_CLASSES = ['Turista', 'Turista Superior', 'Business', 'Primera'];
const OPTIONS_SEARCH = [
    {
        id: 1,
        value: 'Solo ida',
    },
    {
        id: 2,
        value: 'Ida y vuelta',
    },
];

const CURRENCY_CODES = [
    {
        id: 1,
        currency: 'EUR',
        symbol: '€',
        country: 'Union Europea',
    },
    {
        id: 2,
        currency: 'USD',
        symbol: 'US$',
        country: 'Estados Unidos',
    },
    {
        id: 3,
        currency: 'ARS',
        symbol: 'AR$',
        country: 'Argentina',
    },
    {
        id: 4,
        currency: 'CNY',
        symbol: '¥',
        country: 'China',
    },
    {
        id: 5,
        currency: 'NZD',
        symbol: 'NZ$',
        country: 'Nueva Zelanda',
    },
    {
        id: 6,
        currency: 'GBP',
        symbol: '£',
        country: 'Reino Unido',
    },
    {
        id: 7,
        currency: 'JPY',
        symbol: '¥',
        country: 'Japón',
    },
    {
        id: 8,
        currency: 'AUD',
        symbol: 'A$',
        country: 'Australia',
    },
    {
        id: 9,
        currency: 'CAD',
        symbol: 'C$',
        country: 'Canadá',
    },
    {
        id: 10,
        currency: 'CHF',
        symbol: 'CHF',
        country: 'Suiza',
    },
];

const POIS_DESTINATIONS_AVAILABLE = [
    'BCN',
    'SXF',
    'BML',
    'BER',
    'TXL',
    'DAL',
    'ADS',
    'RBD',
    'DFW',
    'LHR',
    'YXU',
    'LCY',
    'STN',
    'BQH',
    'SEN',
    'LGW',
    'LTN',
    'LON',
    'ELS',
    'LOZ',
    'PHT',
    'PRX',
    'JFK',
    'EWR',
    'SWF',
    'NYC',
    'NYS',
    'NYS',
];
const POIS_DESTINATIONS = [
    {
        name: 'Barcelona',
        iataCodes: ['BCN'],
        north: 41.42,
        west: 2.11,
        south: 41.347463,
        east: 2.228208,
    },
    {
        name: 'Berlin',
        iataCodes: ['SXF', 'BML', 'BER', 'TXL'],
        north: 52.541755,
        west: 13.354201,
        south: 52.490569,
        east: 13.457198,
    },
    {
        name: 'Dallas',
        iataCodes: ['DAL', 'ADS', 'RBD', 'DFW'],
        north: 32.806993,
        west: -96.836857,
        south: 32.74031,
        east: -96.737293,
    },
    {
        name: 'London',
        iataCodes: [
            'LHR',
            'YXU',
            'LCY',
            'STN',
            'BQH',
            'SEN',
            'LGW',
            'LTN',
            'LON',
            'ELS',
            'LOZ',
        ],
        north: 51.52018,
        west: -0.169882,
        south: 51.484703,
        east: -0.061048,
    },
    {
        name: 'Paris',
        iataCodes: ['PHT', 'PRX'],
        north: 48.91,
        west: 2.25,
        south: 48.8,
        east: 2.46,
    },
    {
        name: 'New York',
        iataCodes: ['JFK', 'EWR', 'SWF', 'NYC', 'NYS', 'NYS'],
        north: 40.792027,
        west: -74.058204,
        south: 40.697607,
        east: -73.942847,
    },
];

module.exports = {
    FLIGHT_CLASSES,
    OPTIONS_SEARCH,
    CURRENCY_CODES,
    POIS_DESTINATIONS,
    POIS_DESTINATIONS_AVAILABLE,
};
